services:
  envoy:
    image: envoyproxy/envoy:v1.25.1
    container_name: envoy_grpc_proxy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

